feat: UserCircle Entity 설계
CAUCSE/CAUSW_backend pull request #41
Opened 2021-07-17 10:26 UTC by dlsrks1021

## Description
UserCircle entity 기본 구조 작성

## Changes detail

- UserCircle Entity 작성

### Checklist

- [ ] Test case
- [ ] End of work

2021-07-25 08:41 UTC, GunHee5719 requested changes

2021-07-25 08:41 UTC, GunHee5719 commented on src/main/java/net/causw/adapter/persistence/Circle.java
> +    @OneToOne(mappedBy = "managing_circle")
이거 이미 적용해서, 안 해도 될 듯 합니다.

(+) join 거는 쪽의 변수명과 같아야 해서, `managingCircle` 이 맞습니다. 이거 돌려보면 에러날거에요

2021-07-25 08:41 UTC, GunHee5719 commented on src/main/java/net/causw/adapter/persistence/Circle.java
> +    @JoinColumn(name = "user_circle_id", nullable = true)
`nullable=true` 는 default 옵션이라 빼주셔도 될 것 같고, 나머지 컬럼에 `nullable=false` 를 걸어주시는 게 좋을 것 같아요.

2021-07-25 08:41 UTC, GunHee5719 commented on src/main/java/net/causw/adapter/persistence/UserCircle.java
> +        UserCircleStatus status
`User` 이랑 `Circle` 에 대한 값을 받지 않고 있는 것 같습니다.

2021-07-25 08:41 UTC, GunHee5719 commented on src/main/java/net/causw/adapter/persistence/port/UserCirclePortImpl.java
> +        return UserCircleDto.from(this.userCircleRepository.findById(id).orElseThrow(
Throw Exception은 PortImpl 에서 하지 말고, Service에서 해주세요. 여기서는 그대로 Optional 객체로 매핑해서 리턴해주면 될 것 같습니다.

2021-07-25 08:41 UTC, GunHee5719 commented on src/main/java/net/causw/adapter/web/UserCircleController.java
> +@RequestMapping("/api/v1/userCircle")
대소문자 구분이 없어서, `user-circle` 이 좋을 것 같습니다.

2021-07-25 08:41 UTC, GunHee5719 commented on src/main/java/net/causw/adapter/web/UserCircleController.java
> +    public UserCircleDto findById(@PathVariable String id) { return this.userCircleService.findById(id); }
개행자 넣어주세요. 전체적으로 코드 스타일이 안맞는 것 같아서, `Ctrl + a` => `Ctrl + alt + l` 하시면 IntelliJ IDE에서 이쁘게 맞춰줍니다.

2021-07-25 08:41 UTC, GunHee5719 commented on src/main/java/net/causw/adapter/web/UserCircleController.java
> +    public UserCircleDto findById(@PathVariable String id) { return this.userCircleService.findById(id); }
이건 다른 파일들에도 적용해주세요

2021-07-25 08:41 UTC, GunHee5719 commented on src/main/java/net/causw/adapter/persistence/Circle.java
> +    private List<UserCircle> userCircles;
List 형태이기 때문에, 변수명을 `userCircleList` 로 해주셔야 할 것 같아요

2021-07-31 12:24 UTC, GunHee5719 reviewed
이거만 적용되면 머지되어도 좋을 것 같습니다!

2021-07-31 12:24 UTC, GunHee5719 commented on src/main/java/net/causw/adapter/persistence/User.java
> +    private List<UserCircle> userCircles;
여기도 `userCircleList` 로 바꿔주세요

2021-07-31 12:29 UTC, GunHee5719 commented
앗 근데 충돌나네요. 확인 부탁드려요!

2021-08-02 11:56 UTC, GunHee5719 approved these changes
LGTM

2021-08-07 04:51 UTC, ase3238 approved these changes

2021-08-07 04:51 UTC, merged