fix : swagger 상에서 user token header로 받기(검증 X)
CAUCSE/CAUSW_backend pull request #434
Opened 2024-01-25 06:42 UTC by sanggae4133

### 🚩 관련사항
Issue #432 

### 📢 전달사항
기존 Swagger UI에서 user token을 request body로 받으려 해 모든 API 요청 시 request body에 중괄호가 2쌍 생성되어 json parsing error가 발생했었습니다.
SecurityContextHolder.getContext().getAuthentication().getPricipal()을 통해 Swagger UI에서 user token을 통해 상단 Authorize 버튼으로 인증을 하면 자동으로 request header에 user token을 넣어주는 방식으로 변경했습니다.

### 📸 스크린샷
변경 후 Swagger UI
![Uploading edited swagger.png…]()

### 📃 진행사항
- [x] SwaggerConfig.java 변경
- [x] 모든 domain Controller 변경

### ⚙️ 기타사항

개발기간: 약 10시간

2024-01-25 06:51 UTC, pstar987 approved these changes
확인했습니다! 고생하셨어요~

2024-01-25 06:59 UTC, SL313 requested changes
고생 많으셨습니다.

2024-01-25 06:59 UTC, SL313 commented on src/main/java/net/causw/adapter/web/CircleController.java
> +import io.swagger.v3.oas.annotations.Parameter;
저희는 스웨거 springfox 사용 중인데 공식적으로는 v3 지원하지 않는 것으로 알고 있습니다. io.swagger.annotations 패키지 내에서 사용하셔야 할 거 같은데 해당 Import 구문이 어디에 쓰여서 적힌건지 알 수 있을까요?
패키지 버전 관련해서 공식문서 참고해서 봐보시면 좋을 것 같습니다.
https://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/ApiResponse.html
https://docs.swagger.io/swagger-core/v2.1.1/apidocs/io/swagger/v3/oas/annotations/responses/ApiResponse.html

2024-01-25 06:59 UTC, SL313 commented on src/main/java/net/causw/adapter/web/CircleController.java
> +
userId, currentUserId, requestUserId 로 변수명이 각각 다른 이유가 궁금합니다. '기존에 이렇게 되어 있어서' 라는 이유로 놔두신거면 수정 부탁드립니다.

2024-01-25 06:59 UTC, SL313 commented on src/main/java/net/causw/config/swagger/SwaggerConfig.java
> -                .useDefaultResponseMessages(false)
validation 작업으로 인해 제가 추가했던 부분인데 지우신 이유가 따로 있나요?

2024-01-25 06:59 UTC, SL313 commented on src/main/java/net/causw/config/swagger/SwaggerConfig.java
> +                                .build()));
메소드로 따로 빼주시면 좋을 것 같습니다.

2024-01-25 12:57 UTC, sanggae4133 commented on src/main/java/net/causw/config/swagger/SwaggerConfig.java
> -                .useDefaultResponseMessages(false)
따로 없는데, 모르고 삭제한 것 같아요.. 다시 추가했습니다

2024-01-25 13:00 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/web/CircleController.java
> +
currentUserId가 좀 더 사용 목적을 잘 반영하는 변수명인 것 같아이걸로 통일 했습니다.
String currentUserId = ((String) principal);

2024-01-26 00:42 UTC, kitaee approved these changes
고생하셨습니다:)

2024-01-26 00:42 UTC, kitaee commented on src/main/java/net/causw/config/swagger/SwaggerConfig.java
> +import springfox.documentation.service.*;
import할 때 마지막에 *를 붙이는 와일드카드방식은 지양하는 방식이라고 들었어요
https://dev.to/kingori/import-5531
여기 한번 읽어보시고 특별한 이유가 아니면 수정 부탁드립니다.

2024-01-26 08:20 UTC, SL313 approved these changes
제 코멘트에 따른 변경사항 확인했습니다! 고생하셨습니다 :)

2024-01-26 08:25 UTC, realisshomyang approved these changes
LGTM👍

2024-01-26 08:44 UTC, merged