feat : 게시판 API 검증 및 swagger 보강 / user token header 삽입 적용
CAUCSE/CAUSW_backend pull request #435
Opened 2024-01-26 14:34 UTC by pstar987

### 🚩 관련사항

### 📢 전달사항
게시판 생성, 검색, 업데이트, 삭제, 복구 API를 검증한 뒤 swagger 문서를 보강했습니다.
user token을 header에서 받을 수 있도록 수정해 놓았습니다.
추후 오류 코드에 관한 api response도 추가할 예정입니다.

findAll 메서드가 circle의 게시판을 제외하고 검색하는 기능으로 쿼리문이 생성되어 있어서 메서드 명 그대로 모든 게시판을 불러올 수 있도록 쿼리를 생성해 적용했습니다.

### 📸 스크린샷
![스크린샷 2024-01-26 오후 11 27 09](https://github.com/CAUCSE/CAUSW_backend/assets/63050966/41e37654-1ee7-4964-982d-f791f923c0aa)

### 📃 진행사항
- [ ] 게시판 생성 검증 완료(사용 가능 / 오류 코드 api response 보강 예정)
- [ ] 게시판 검색 검증 완료(사용 가능 / 오류 코드 api response 보강 예정)
- [ ] 게시판 업데이트 검증 완료(사용 가능 / 오류 코드 api response 보강 예정)
- [ ] 게시판 삭제 검증 완료(사용 가능 / 오류 코드 api response 보강 예정)
- [ ] 게시판 복구 검증 완료(사용 가능 / 오류 코드 api response 보강 예정)
- [ ] 게시판 DB 수정(현재 not null 인 circle_id 를 null 로 변경, user_id 추가)

### ⚙️ 기타사항
초기 dto 스웨거 설정 과정에서 createRoleList의 example을 string으로 수정하여서 다시 list로 변경후 commit 하였습니다.

개발기간: 5시간

2024-01-27 04:24 UTC, kitaee approved these changes

2024-01-27 04:24 UTC, kitaee commented on src/main/java/net/causw/adapter/web/BoardController.java
> +import org.springframework.web.bind.annotation.*;
이거 전에 상제 PR에도 얘기해줬는데 *로 받는 wildcard 방식은 추후에 유지보수 입장에서 지양하는 입장이에요.
https://dev.to/kingori/import-5531
이거 읽어보고 비록 코드가 간결해지는 장점이 있지만 명확하게 import 대상을 지정해주는게 좋을겁니다.

2024-01-27 04:24 UTC, kitaee commented on src/main/java/net/causw/adapter/web/BoardController.java
> +        String userId = ((String) principal);
흠 여기 뿐만 아니라 다른 곳에도 각 userId를 이름을 달리해줬는데 상제 쪽에서는 currentUserId? 였나 그거 사용했을거에요. 결국에 이 userId의 유래는 Spring Security 컨텍스트안에 담겨있는 즉 로그인 되어있는 유저이기 때문에 메소드가 달라지더라도 그냥 전체 컨트롤러에서 통일하는게 좋다는 개인적인 생각입니다.

상제쪽이랑 맞추던지 아니면 백엔드팀에서 따로 시큐리티 컨텍스트에 담겨있는 유저 변수명을 맞추는게 좋을 것 같아요 제 리뷰 보는 다른 사람들의 의견도 궁금합니다.

2024-01-27 05:11 UTC, pstar987 commented on src/main/java/net/causw/adapter/web/BoardController.java
> +import org.springframework.web.bind.annotation.*;
넵 확인했습니다!

2024-01-27 05:18 UTC, pstar987 commented on src/main/java/net/causw/adapter/web/BoardController.java
> +        String userId = ((String) principal);
통일하는 편이 오히려 id 값이 로그인한 유저라는 것을 확실히 알 수 있을것 같아서 좋을 것 같습니다!

2024-01-27 05:26 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/web/BoardController.java
> +        String userId = ((String) principal);
currentUserId 가 더 나을 것 같습니다 아무래도 그냥 userId로 사용하게 되면 api 요청하는 주체와 객체 유저의 혼동이 있을 거 같아요

2024-01-27 05:27 UTC, sanggae4133 approved these changes
기태형이 코멘트 단 부분만 수정하면 다른데는 좋은 것 같습니다 고생하셨어요

2024-01-27 06:03 UTC, SL313 requested changes
고생하셨습니다. 코멘트 참고해서 수정해주시고, 달리 생각되는 부분은 언제든 말씀해주시면 되겠습니다.

2024-01-27 06:03 UTC, SL313 commented on src/main/java/net/causw/adapter/web/BoardController.java
>      ) {
검증 및 명세 작업하시면서 create -> createBoard 와 같이 API명을 더 정확하게 적어주시면 좋을 것 같습니다. 민규님 외에도 저를 포함해 다른 분들도 마찬가지입니다.

2024-01-27 06:03 UTC, SL313 commented on src/main/java/net/causw/application/dto/board/BoardCreateRequestDto.java
> +    @ApiModelProperty(value = "Board 설명", example = "board_description")
Board 를 게시판이라고 정정해주시면 감사하겠습니다.

2024-01-27 06:03 UTC, SL313 commented on src/main/java/net/causw/application/dto/board/BoardCreateRequestDto.java
>      private String circleId;
해당 게시판이 속한 동아리의 고유 id 값이라는 말씀이시죠? api 명세는 프론트에서 확인해야 되는 부분인데 재차 물어보는 일이 없도록 명세에 최대한 자세하게 적어주셔야 할 것 같습니다. example 예시 또한 실제 예시를 적어주셔야 합니다. (혹은 uuid의 String 형식이다 등등 자세하게)

2024-01-28 06:08 UTC, pstar987 commented on src/main/java/net/causw/adapter/web/BoardController.java
> +        String userId = ((String) principal);
확실히 구분할 수 있는 이름으로 통일하면 괜찮을 것 같습니다.

2024-01-28 06:09 UTC, pstar987 commented on src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
해당 쿼리부분은 추후에 기능 변경에 따라서 사용할 수도 있을 것 같아서 남겨두었는데 그래도 삭제해두고 나중에 생성하는 편이 나을까요?

2024-01-28 06:22 UTC, pstar987 commented on src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
> +
삭제된 게시판을 확인하는 부분은 생각을 못했네요.. 관리자 권한인 경우에만 파라미터로 삭제된 게시판도 볼 수 있게 한다면 좋을 것 같습니다

2024-01-28 06:24 UTC, pstar987 commented on src/main/java/net/causw/application/dto/board/BoardCreateRequestDto.java
>      private String circleId;
속한 동아리의 고유 id 맞습니다. 자세히 적어놓겠습니다

2024-01-28 06:25 UTC, pstar987 commented on src/main/java/net/causw/application/dto/board/BoardCreateRequestDto.java
> +    @ApiModelProperty(value = "Board 설명", example = "board_description")
넵 정정해놓겠습니다

2024-01-28 06:25 UTC, pstar987 commented on src/main/java/net/causw/adapter/web/BoardController.java
>      ) {
넵 확인했습니다

2024-01-28 06:27 UTC, pstar987 commented on src/main/java/net/causw/adapter/web/BoardController.java
> +    public List<BoardResponseDto> findAll() {
넵 맞습니다. 수정하겠습니다

2024-01-28 14:26 UTC, SL313 commented on src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
넵 필요에 따라 생성하는 것이 낫겠습니다

2024-01-28 14:26 UTC, SL313 commented on src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
> +
네네 다른 분들 의견 받고 진행하죠

2024-01-28 14:40 UTC, pstar987 commented on src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
넵 확인했습니다

2024-01-29 00:32 UTC, kitaee commented on src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
> +
좋네여 인자로 받는편이 확장성이 좋을듯

2024-01-29 00:33 UTC, kitaee commented on src/main/java/net/causw/adapter/web/BoardController.java
> +        String userId = ((String) principal);
loginUser 좋습니다

2024-01-29 00:37 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/persistence/repository/BoardRepository.java
> +
오 저도 인자가 나을 것 같아요 좋습니다!

2024-01-29 00:38 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/web/BoardController.java
> +        String userId = ((String) principal);
음 저도 loginUser가 의미 상으로나 세련됨으로나 더 나은 것 같아요 아이디어 굿!

2024-01-29 05:55 UTC, pstar987 commented on src/main/java/net/causw/adapter/web/BoardController.java
> +        String userId = ((String) principal);
id값이니 loginUserId라고 확실히 명명하는 편이 좋지 않을까요?

2024-01-29 05:59 UTC, realisshomyang commented on src/main/java/net/causw/adapter/web/BoardController.java
> +        String userId = ((String) principal);
loginUserId로 명시하는 편이 나은 것 같습니다!

2024-01-29 06:52 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/web/BoardController.java
> +        String userId = ((String) principal);
아 그 저도 loginUserId가 나을 거 같습니다

2024-01-29 12:04 UTC, pstar987 commented
코멘트 사항에 따라 수정하였습니다. 확인부탁드립니다.

2024-01-29 12:12 UTC, pstar987 commented
죄송합니다... 동아리장 권한 관련해서 문제가 생겨서 다시 확인해보겠습니다..

2024-01-29 13:21 UTC, pstar987 commented
쿼리문 수정하여 구현 완료하였습니다. 확인 부탁드립니다.

2024-01-30 01:33 UTC, kitaee commented
고생했어요~

2024-01-30 04:05 UTC, sanggae4133 approved these changes
확인했습니다 오버라이딩 부분만 다른 분들이 봐주심 더 좋을 것 같아요!

2024-01-30 09:40 UTC, realisshomyang commented on src/main/java/net/causw/adapter/persistence/port/board/BoardPortImpl.java
> +
오름차순 정렬해놓고 합쳤는데 정렬 한 번 더 안하는지 ?

2024-01-31 08:55 UTC, merged