Refactor/circle PR
CAUCSE/CAUSW_backend pull request #438
Opened 2024-02-05 14:30 UTC by sanggae4133

### 🚩 관련사항

### 📢 전달사항
Circle Domain 관련 Swagger 문서 보강 및 API 작동 검증

### 📸 스크린샷

### 📃 진행사항
- [ ] done1 Circle Domain Swagger 문서 보강

### ⚙️ 기타사항

개발기간: 
약 2주

2024-02-06 05:02 UTC, pstar987 commented on src/main/java/net/causw/application/dto/circle/CircleBoardsResponseDto.java
다른 value 값들 처럼 'circleresponsedto' -> '동아리 정보' 이런식으로 작성하는 편이 좋을 수도 있을 것 같습니다..! 그리고 'List<BoardOfCircleResponseDto'에 '>'빠져 있네요 간단한 오탈자라 추가해주시면 될 것 같습니다

2024-02-06 05:21 UTC, pstar987 requested changes
수고하셨습니다~ 코멘트 읽어주시고 혹시 제가 잘못생각한 부분있으면 말씀해주세요!

2024-02-06 05:21 UTC, pstar987 commented on src/main/java/net/causw/application/dto/circle/CircleBoardsResponseDto.java
> +    @ApiModelProperty(value ="CircleResponseDto", example = "동아리 responseDTO 객체를 반환합니다.")
다른 value 값들 처럼 'circleresponsedto' -> '동아리 정보' 이런식으로 작성하는 편이 좋을 수도 있을 것 같습니다..!

2024-02-06 05:21 UTC, pstar987 commented on src/main/java/net/causw/application/dto/circle/CircleBoardsResponseDto.java
> +    @ApiModelProperty(value ="List<BoardOfCircleResponseDto", example = "동아리의 속한 게시판 목록을 List<BoardOfCircleResponseDto 객체(리스트)로 반환합니다.")
그리고 'List<BoardOfCircleResponseDto'에 '>'빠져 있네요 간단한 오탈자라 추가해주시면 될 것 같습니다

2024-02-06 05:21 UTC, pstar987 commented on src/main/java/net/causw/application/dto/circle/CirclesResponseDto.java
> -        );
단순 질문입니다. 해당 부분을 삭제한 이유를 알고 싶습니다! joined 변수를 삭제하면서 필요가 없어진 것일까요?

2024-02-06 05:21 UTC, pstar987 commented on src/main/java/net/causw/adapter/web/CircleController.java
> +import io.swagger.annotations.*;
이부분은 수정하시면 될것 같습니다~

2024-02-06 05:21 UTC, pstar987 commented on src/main/java/net/causw/adapter/web/CircleController.java
> +    @ApiResponses({
전체적으로 validation 응답값이 추가 되어야할 것 같습니다. 지금은 성공한 경우에 대해서만 실행을 하네요

2024-02-06 08:28 UTC, sanggae4133 commented on src/main/java/net/causw/application/dto/circle/CircleBoardsResponseDto.java
> +    @ApiModelProperty(value ="List<BoardOfCircleResponseDto", example = "동아리의 속한 게시판 목록을 List<BoardOfCircleResponseDto 객체(리스트)로 반환합니다.")
수정했습니다

2024-02-06 08:28 UTC, sanggae4133 commented on src/main/java/net/causw/application/dto/circle/CircleBoardsResponseDto.java
> +    @ApiModelProperty(value ="CircleResponseDto", example = "동아리 responseDTO 객체를 반환합니다.")
수정했습니다

2024-02-06 08:29 UTC, sanggae4133 commented on src/main/java/net/causw/application/dto/circle/CirclesResponseDto.java
> -        );
joined 변수가 현재 코드에서 사용하지 않기 때문에 삭제하면서 joined 변수가 없으면 생성자 2개가 중복되기 때문에 하나는 삭제했습니다

2024-02-06 08:32 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/web/CircleController.java
> +import io.swagger.annotations.*;
수정했습니다

2024-02-06 10:31 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/web/CircleController.java
> +    @ApiResponses({
반영했습니다.

2024-02-06 10:31 UTC, sanggae4133 commented on src/main/java/net/causw/application/dto/circle/CirclesResponseDto.java
> -        );
그랬는데 그냥 원래대로 롤백했어요 혹시 몰라서

2024-02-06 13:50 UTC, pstar987 commented on src/main/java/net/causw/application/dto/circle/CirclesResponseDto.java
> -        );
아하 넵 감사합니다

2024-02-07 10:39 UTC, realisshomyang approved these changes
고생하셨습니다.  User role 부분 이슈 파서 계속 진행하면 될 것 같습니다!

2024-02-07 10:39 UTC, realisshomyang commented on src/main/java/net/causw/application/circle/CircleService.java
> +        // https://www.inflearn.com/questions/21303/enum%EC%9D%84-list%EB%A1%9C-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%B0%9B%EB%8A%94%EC%A7%80-%EA%B6%81%EA%B8%88%ED%95%A9%EB%8B%88%EB%8B%A4
이 부분은 이슈로 따로 뺴놓는게 어떤지요 ? 조금 큰 문제긴 하니까 참고 자료로 올려놓은 다음에 그 role 부분 개선하는 브랜치 따로 파는게 좋을 것 같아요!

2024-02-08 04:20 UTC, merged