fix : 댓글 및 대댓글 기능 개선
CAUCSE/CAUSW_backend pull request #542
Opened 2024-04-01 15:43 UTC by zestbear

### 🚩 관련사항
#539 

### 📢 전달사항

댓글과 대댓글의 기능을 개선하려고 합니다.

특정 게시물의 모든 댓글 수를 가져오는 쿼리를 작성하였습니다. 수정해야 할 부분이 있다면 알려주세요.
- 댓글이 삭제되어도 댓글에 달려 있던 대댓글은 유지
- 게시물/댓글/대댓글 join하여 한방 쿼리로 count

### 📸 스크린샷
<img width="1281" alt="image" src="https://github.com/CAUCSE/CAUSW_backend/assets/49549887/9f9a7b22-c502-47af-87a1-ef246001b2c7">

### 📃 진행사항
- [x] 특정 게시물의 모든 댓글 개수 반환하도록 수정 (댓글+대댓글)
- [x] 댓글 반환 시 댓글에 달린 대댓글 함께 반환하도록 수정

### ⚙️ 기타사항

- 댓글 조회에 대댓글 조회를 포함시켰기 때문에 대댓글 조회 기능을 삭제하였습니다.

개발기간: 1주

2024-04-02 03:28 UTC, pstar987 approved these changes
고생하셨습니다! 한번에 댓글 대댓글 묶어서 보여줘서 확인하는데 훨씬 좋을것 같네요!

2024-04-02 14:57 UTC, realisshomyang approved these changes
childCommentDomainModel DTO로 매핑하는 곳에서 함수 명 통일 확인해주시는 것 빼고 문제 없어 보입니다! 고생하셨습니다.

2024-04-02 14:57 UTC, realisshomyang commented on src/main/java/net/causw/adapter/persistence/port/comment/CommentPortImpl.java
>  @Component
아 저희 코드 상에 문제(?)는 아닌데 생성자 주입을 현재 옛날 방식으로 하고 있어서
@ReqiredArgsConstructor
리팩토링이나 코드 구현할 때 틈틈히 바꿔주시면 감사드리겠습니다!

2024-04-02 14:57 UTC, realisshomyang commented on src/main/java/net/causw/application/comment/CommentService.java
> +                        .map(ChildCommentResponseDto::new)
저희 코드 상에서 new로 call dto를 변환하기 보다는 
from으로 통일을 해놨습니다!
다른 dto 한 번 참고해주시면 감사하겠습니다!

2024-04-02 15:03 UTC, realisshomyang commented on src/main/java/net/causw/application/comment/CommentService.java
> +                        .map(ChildCommentResponseDto::new)
물론 이제 리팩토링 과정에서 @builder 패턴을 적용할 것 같긴한데 , 함수 명을 통일하는 게 좋을 것 같다는 의견입니다. 
다른 분들 의견은 어떠신가요?

2024-04-03 05:18 UTC, SL313 requested changes
고생많으셨습니다! 명근님 요청하신 함수명 관련 이야기 끝난 후에 반영되면 좋을 것 같습니다~

2024-04-03 05:18 UTC, SL313 commented on src/main/java/net/causw/adapter/persistence/repository/PostRepository.java
> +            "and (cc.is_deleted = false or cc.is_deleted is null)", nativeQuery = true)
예약어는 대문자로 써주시면 더 좋을 것 같습니다!

2024-04-03 05:18 UTC, SL313 commented on src/main/java/net/causw/application/comment/CommentService.java
> +                        .map(ChildCommentResponseDto::new)
함수명을 통일한다는게 정확히 무슨 뜻일까용?? 참고 예시 하나만 부탁드립니다!

2024-04-03 06:55 UTC, realisshomyang commented on src/main/java/net/causw/application/comment/CommentService.java
> +                        .map(ChildCommentResponseDto::new)
ChildCommentResponseDto::from

다른 Dto 보면 다 from으로 함수 통일 되어 있어서요

2024-04-03 08:12 UTC, zestbear commented on src/main/java/net/causw/application/comment/CommentService.java
> +                        .map(ChildCommentResponseDto::new)
말씀 해주신 대로 코드를 통일했어야 했는데, 생각이 짧았던 것 같습니다. 함수명 from으로 통일하여 수정하였습니다 :)

2024-04-03 08:13 UTC, zestbear commented on src/main/java/net/causw/adapter/persistence/repository/PostRepository.java
> +            "and (cc.is_deleted = false or cc.is_deleted is null)", nativeQuery = true)
예약어 대문자로 수정하였습니다!

2024-04-03 08:33 UTC, sanggae4133 approved these changes
좋은 방향으로 리펙토링 한 것 같습니다 적지 않게 걸렸을텐데 고생 많으셨습니다

2024-04-07 06:36 UTC, SL313 approved these changes
확인했습니다! 늦어서 죄송합니다 ㅠㅠ

2024-04-07 10:58 UTC, merged