refactor : 회원가입 기능 리팩토링
CAUCSE/CAUSW_backend pull request #577
Opened 2024-08-12 09:53 UTC by OH-GITAEK

### 🚩 관련사항
#573 

### 📢 전달사항
새로 추가된 필드 (전화번호, 학부/학과, 학적상태, 현재 등록 완료된 학기, 졸업시기(년), 졸업시기(월)) 추가
학적상태를 나타내기 위한 enum추가
회원가입 과정에서 닉네임 중복 확인

이렇게 구현했습니다!!
아래에 테스트 결과 첨부하겠습니다

### 📸 스크린샷
![image](https://github.com/user-attachments/assets/27e5b22e-6d45-4342-beef-13840329d582)
![image](https://github.com/user-attachments/assets/b5381927-c4bf-4815-9523-8fead23e2623)

닉네임 중복시 에러
![image](https://github.com/user-attachments/assets/b42ddd9b-9554-4c87-8a2b-9d0a5879d677)

### 📃 진행사항

### ⚙️ 기타사항
기타 참고사항을 적어주세요.

개발기간:

2024-08-13 04:29 UTC, pstar987 requested changes
수고하셨습니다~ 근데 혹시 usercontroller에 preauthorize로 적용해둔 부분은 따로 지우신 이유가 있을까요?

2024-08-13 06:56 UTC, sinseongseop commented
Figma의 회원가입 폼과 RequestDto 비교해서 확인 완료했습니다.  회원가입에서 추가로 필요한 특성들 이 모두 추가 된것 같습니다. 수고 많으셨습니다!

2024-08-13 09:15 UTC, OH-GITAEK commented
#

> 수고하셨습니다~ 근데 혹시 usercontroller에 preauthorize로 적용해둔 부분은 따로 지우신 이유가 있을까요?

중간에 개발환경이 바뀌면서 빠진것 같습니다!
다시 적용해서 푸쉬했습니다!!

2024-08-13 09:17 UTC, OH-GITAEK commented
> 수고하셨습니다~ 근데 혹시 usercontroller에 preauthorize로 적용해둔 부분은 따로 지우신 이유가 있을까요?

중간에 개발환경이 한번  바뀌면서 누락된 것 같습니다!
다시 추가해서 푸쉬해두었습니다!!

2024-08-13 09:19 UTC, pstar987 approved these changes
넵 고생하셨습니다~

2024-08-13 14:03 UTC, zestbear approved these changes
확인했습니다. 수고 많으셨습니다~ :)

2024-08-14 02:26 UTC, OH-GITAEK commented on src/main/java/net/causw/adapter/persistence/user/User.java
> +    @Column(name = "phone_number", nullable = true)  // 일단 null 가능하게 설정(false 로 하면 기존 데이터와 충돌 예상)
넵! 감사합니다

2024-08-15 08:54 UTC, realisshomyang approved these changes
고생하셨습니다 ~ 머지하겠습니다!

2024-08-15 08:54 UTC, merged