refactor : 게시판 메인 페이지 리팩토링(전체 게시판 조회)
CAUCSE/CAUSW_backend pull request #582
Opened 2024-08-15 06:31 UTC by OH-GITAEK

### 🚩 관련사항
https://github.com/CAUCSE/CAUSW_backend/issues/578

### 📢 전달사항
새로 변경된 기획에 맞게 전체 게시판을 조회할 경우 각 게시판에 가장 최근의 글 3개가 보이도록 변경하였습니다.
이 과정에서 프론트 담당자분과 상의하에 새로운 필드를 하나 추가하였습니다!
또한 기존에 리턴으로 넘겨주던 resposeDto와 변경사항이 많고 기존의 dto가 다른곳에서도 많이 사용되어 새로운 Dto를 추가하여 사용했습니다

### 📸 스크린샷
![image](https://github.com/user-attachments/assets/9708a60f-7528-440d-a372-78c0fd73b044)

### 📃 진행사항

### ⚙️ 기타사항
기타 참고사항을 적어주세요.

개발기간:

2024-08-15 06:40 UTC, acidify04 commented
필요한 부분 정확하게 잘 만들어주신 것 같습니다! 고생하셨습니다 👍

2024-08-15 06:42 UTC, givemethatsewon commented
상의한 포맷대로 잘 넘어오네요! 좋습니다 :)

2024-08-15 11:29 UTC, pstar987 requested changes

2024-08-15 11:29 UTC, pstar987 commented on src/main/java/net/causw/adapter/web/BoardController.java
> +    public List<BoardMainResponseDto> findAllBoard(
기존 findAll은 모든 게시판을 조회하는 메서드입니다. 이번에 작업해주신 부분은 기존에 있던 findAll을 아예 변경해버리신것 같은데 기존 findAll과 별도로 생성해주시는 편이 추후를 위해서 좋을 것 같습니다.

2024-08-15 11:29 UTC, pstar987 commented on src/main/java/net/causw/application/board/BoardService.java
> +    public List<ContentDto> findRecentThreePosts(User user, String boardId) {
dto의 이름도 단순히 contentdto가 아닌 PostContentDto인 것으로 확실히 명시해주시길 바랍니다. 또한 게시글과 관련된 로직으로 boardservice가 아니라 postservice에서 사용하는 것이 맞다고 생각이 드는데 다른 분들 의견이 궁금합니다!

2024-08-15 11:29 UTC, pstar987 commented on src/main/java/net/causw/application/board/BoardService.java
> -        if (roles.contains(Role.ADMIN) || roles.contains(Role.PRESIDENT)) {
이부분도 변경하면서 로직상으로 누락된 것이 없는지 확인해주시면 감사하겠습니다. 확인 후에는 간단한 설명도 부탁드립니다. 기존 관리자 권한이 삭제된 게시판도 확인 가능하도록 만들어둔 로직이었습니다.

2024-08-15 11:40 UTC, OH-GITAEK commented on src/main/java/net/causw/adapter/web/BoardController.java
> +    public List<BoardMainResponseDto> findAllBoard(
넵 수정하겠습니다!

2024-08-15 11:42 UTC, OH-GITAEK commented on src/main/java/net/causw/application/board/BoardService.java
> +    public List<ContentDto> findRecentThreePosts(User user, String boardId) {
dto이름 수정하겠습니다!
boardservice에 로직을 작성한 이유로는 저도 처음에는 같은 생각으로 postservice에 만들었다가 서비스계층간의 상호참조를 피하기 위해 수정했습니다! 이부분도 수정 필요하다면 수정하겠습니다!!
리뷰 감사합니다!!

2024-08-15 11:46 UTC, OH-GITAEK commented on src/main/java/net/causw/application/board/BoardService.java
> -        if (roles.contains(Role.ADMIN) || roles.contains(Role.PRESIDENT)) {
이부분은 같은 부분 맡은 팀원들과 이야기하며 기획에도 따로 구분이 없어 뺐었는데 확인 후 뺐어야 하는데 죄송합니다.
추가해서 다시 푸쉬하겠습니다!

2024-08-16 09:29 UTC, realisshomyang commented on src/main/java/net/causw/application/board/BoardService.java
> +    public List<ContentDto> findRecentThreePosts(User user, String boardId) {
수정되었나요?

2024-08-16 12:27 UTC, OH-GITAEK commented on src/main/java/net/causw/application/board/BoardService.java
> +    public List<ContentDto> findRecentThreePosts(User user, String boardId) {
아직 수정중입니다! postservice로 옮기면 되는것일까요?

2024-08-17 04:42 UTC, OH-GITAEK commented
피드백 사항들 수정해서 푸쉬했습니다!
변경사항
1. findAll복구 시키고 별도의 api 생성
2. dto 이름 ContentDto -> PostContentDto로 변경
3. findRecentThreePosts삭제 => 불필요한 부분과 중복되는 부분이 많아 간단하게 만들어 mainBoard메서드 안에 추가함
4. 관리자 권한이 삭제된 게시판도 확인 가능하도록 로직 변경

2024-08-18 12:40 UTC, sanggae4133 approved these changes
확인했습니다 기획사항 맞춰 잘 구현하신 것 같습니다 고생하셨습니다

2024-08-18 14:05 UTC, pstar987 approved these changes
수정사항 반영까지 고생하셨습니다~!

2024-08-21 11:54 UTC, realisshomyang approved these changes
고생하셨습니다!

2024-08-21 11:54 UTC, zestbear approved these changes

2024-08-21 11:54 UTC, merged