feat: 게시글/댓글 좋아요 기능 , 게시글 즐겨 찾기 기능 및 익명/질문글 기능 추가
CAUCSE/CAUSW_backend pull request #586
Opened 2024-08-17 17:40 UTC by sinseongseop

### 🚩 관련사항
feat/581
https://github.com/CAUCSE/CAUSW_backend/issues/581

### 📢 전달사항
-변경된 ER 다이어그램 (게시글, 댓글 부분만)
https://www.erdcloud.com/d/h2ctuAxhfenNXdqeF
ER 다이어그램을 제가 설계한 후, 동현님한테 피드백을 받았습니다. 최종 확정된 ER 다이어그램입니다.

 -  ApI 명세서 
[게시글_댓글.pdf](https://github.com/user-attachments/files/16645656/_.pdf)
초기 APi 설계는 제가하였고, 동현님과 함께 수정 한 후,  동현님께서 최종 정리 해 주셨습니다.

-  소프트웨어 개발 원칙 중 Kiss와 YAGNI의 원칙 기반으로 개발하여 최대한 단순하면서도, 필요한 모든 기능을 구현하려고 노력했습니다. 

- 게시글/댓글 파트 중 Figma의 디자인에 맞게 구성하기 위한 새로운 기능들을 추가하였습니다.  게시글과 댓글의 좋아요 기능 , 게시글 즐겨 찾기, 취소 기능, 익명과 질문글 기능을 개발 하였습니다.

- 좋아요 기능의 경우 에브리타임의 좋아요 시스템을 기준으로 생각해서 , 좋아요 취소 기능은 만들지 않았습니다. 추후 필요시 추가적인 기능 설계가 필요합니다.

- Valiidation Bucket 제거 리팩토링 코드가 아직 통합되지 않아서, 검증 관련 로직은 추후 필요시 수정이 필요해 보입니다.  우선 단순 검증 로직은 넣어 놨고, FIXME 주석을 통해 해당 파트는 주석을 남겨 놓았습니다.

-  추후 좋아요, 즐겨찾기, 댓글 수 통계 쿼리로 인한 성능 저하가 발견 될 시, 반정규화를 통한 성능향상 리팩토링을 진행하면 좋을거 같습니다.

### 📸 스크린샷
각각의 API의 Test 결과를  issue의 comment로 달아 놓았습니다. 테스트 결과 확인 부탁드립니다.

### 📃 진행사항
- [x] 게시판, 댓글, 대댓글 좋아요 기능 추가 (Create) 및 관련 API 완성
- [x] 게시글 즐겨찾기 저장, 취소 기능 추가(Create, put) 및 관련 API 완성
- [x]  익명, 질문글 기능 추가 및 관련 Request, Response 변경 완료
- [x] 질문글 + 댓글1개이상일떄 ResponseDTO의 updatable, deletable을 False로 변경하는 로직 설계 완성 
- [x]  API 명세서에 나온대로 기능 구현 및 동작 Test 완료, 

### ⚙️ 기타사항
가장 기본적인 기능 위주로 설계하였습니다.  

개발기간:

2024-08-18 12:51 UTC, sanggae4133 reviewed
코드 확인했습니다 고생하셨습니다!

2024-08-18 12:51 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/persistence/repository/CommentRepository.java
> +    boolean existsByPostIdAndIsDeletedFalse(String postId);
기본형 대신에 참조형 변수로 리턴하는 쪽이 추후 확장성 등을 고려해서 더 나을 것 같습니다!

2024-08-18 12:51 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/persistence/repository/FavoritePostRepository.java
> +    boolean existsByPostIdAndUserId(String postId, String userId);
여기도 참조형으로 리턴이 어떨까요?

2024-08-18 12:51 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/persistence/repository/LikeChildCommentRepository.java
> +    boolean existsByChildCommentIdAndUserId(String childCommentId, String userId);
여기도 참조형 어떨까요?

2024-08-18 12:51 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/persistence/repository/LikeCommentRepository.java
> +    boolean existsByCommentIdAndUserId(String commentId, String UserId);
여기도 참조형 어떨까요?

2024-08-18 12:51 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/persistence/repository/LikePostRepository.java
> +    boolean existsByPostIdAndUserId(String postId, String userId);
여기도 참조형 어떨까요?

2024-08-18 14:21 UTC, pstar987 requested changes
고생하셨습니다! 다른분들 피드백 확인하고 반영하면 될것 같습니다~

2024-08-18 14:21 UTC, pstar987 commented on src/main/java/net/causw/adapter/persistence/comment/LikeChildComment.java
> +    private User user;
일반적으로 댓글을 조회할 때 좋아요도 함께 보여줄 텐데 지연 로딩으로 해서 쿼리를 2번 호출하는 것보단 즉시 로딩으로 접근하는 편이 좋다고 알고있는데 다른 분들 의견 함께 들어보고 적절한 것으로 수정하면 좋을 것 같습니다!

2024-08-18 14:31 UTC, givemethatsewon commented
![image](https://github.com/user-attachments/assets/02cf2f2d-9f8f-40cd-b30c-eb8404d02012)
게식시글 생성할 때 투표글과 신청서 글 여부도 선택할 수 있는 것으로 봤는데  isVote, isApply도 있어야 하지 않을까요? 한번 확인 부탁드립니다!

2024-08-18 14:57 UTC, sinseongseop commented
*민세원님 Comment에 대한 답변입니다. 
Figma를 보면 게시글 생성 쪽에 투표글 or 신청서을 작성하는 기능이 있어서 미래에 세원님이 말씀하시는 걸 추가해야 할 수도 있습니다.  다만 지금 개발이 진행된 상황에서 완성된 것은 좋아요/즐겨찾기 기능 뿐이고,세원님이 말씀하시는 것들은 아직 구현이 안되었고 다른 분들이 개발 해 주시기 떄문에, 해당기능을 구현하는 분의 설계에따라 필요성이 달라집니다. YAGNI 원칙에 따르면 프로그래머가 필요하다고 간주할 때까지 기능을 추가하지 않는 것이 좋기 떄문에, 미래에 기능이 만들어 진후  변경해도 충분하다고 생각됩니다.

2024-08-18 15:25 UTC, givemethatsewon commented on src/main/java/net/causw/adapter/persistence/comment/LikeChildComment.java
> +    private User user;
쿼리가 한 번만 실행되는게 성능 상 이점이 있을 것 같습니다!

2024-08-18 15:27 UTC, givemethatsewon commented
음 다른 이슈에서 작업하시겠다는 말씀이신가요?

2024-08-18 16:00 UTC, sinseongseop commented on src/main/java/net/causw/adapter/persistence/repository/CommentRepository.java
> +    boolean existsByPostIdAndIsDeletedFalse(String postId);
요청하신 부분 모두 boolean을 Boolean(참조형)으로 변경 작업 완료했습니다!

2024-08-19 04:03 UTC, pstar987 commented
> ![image](https://private-user-images.githubusercontent.com/86864525/358913194-02cf2f2d-9f8f-40cd-b30c-eb8404d02012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDAzNjQsIm5iZiI6MTcyNDA0MDA2NCwicGF0aCI6Ii84Njg2NDUyNS8zNTg5MTMxOTQtMDJjZjJmMmQtOWY4Zi00MGNkLWIzMGMtZWI4NDA0ZDAyMDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA0MDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZWU2NTQzODMyMTQ5NTAwYzFlZTNmNjE5N2E1Yzg3Y2M2MjRmMmM2NWI1ZDcyMWZkN2FkYjBkZGIxNzBlNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PDMO-XB-0BdXTfcFLNpELnET05_Q8em3v-Lm3uWYVHI) 게식시글 생성할 때 투표글과 신청서 글 여부도 선택할 수 있는 것으로 봤는데 isVote, isApply도 있어야 하지 않을까요? 한번 확인 부탁드립니다!

제가 현재 게시글의 신청서 생성을 작업하고 있는데 이부분은 제가 완료한 후에 isApply를 추가해서 연결하는 등의 방식으로 진행하거나 아예 별도 api를 호출해서 게시글과 별도로 생성을 해도 될것 같습니다

2024-08-19 06:25 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/persistence/comment/LikeChildComment.java
> +    private User user;
음 제가 현재 코드를 이해하기론 Comment나 ChildComment의 pk를 가지고 쿼리를 날려서 LikePost/LikeComment/LikeChildComment의 수를 countBy 집계해 좋아요를 보여주는 걸로 이해했는데,
이 경우 오히려 즉시로딩 하면 성능이 더 저하되지 않을까요?

2024-08-19 06:25 UTC, sanggae4133 commented on src/main/java/net/causw/adapter/persistence/repository/FavoritePostRepository.java
> +    Long countByPostIdAndIsDeletedFalse(String postId);
현재 쿼리들의 파라미터가 객체의 id(pk)로 되어 있는데 객체 자체로 조회하는게 추후 service 레이어 등에서 사용할 때 굳이 객체의 getter를 사용하지 않고도 바로 쿼리를 사용할 수 있어 확장성이나 성능 면에서 더 우수하지 않을까요?
해당 사항은 다른 분들 의견도 궁금합니다!

2024-08-19 06:39 UTC, pstar987 commented on src/main/java/net/causw/adapter/persistence/comment/LikeChildComment.java
> +    private User user;
아 그렇겠네요 어차피 countby로 조회를 해야한다면 그대로 지연로딩 사용하는게 좋을 것 같습니다

2024-08-19 06:45 UTC, pstar987 commented on src/main/java/net/causw/adapter/persistence/repository/FavoritePostRepository.java
> +    Long countByPostIdAndIsDeletedFalse(String postId);
객체 자체로 조회하는 것이 편할 순 있어도 jpa가 결국엔 식별자를 추출해서 조회하는 과정에서 성능상으로는 더 떨어질 수 있다고 알고 있습니다. 그리고 현재 쿼리들이 pk로 통일되어 있기 때문에 그대로 유지하는편이 좋을 것 같다고 생각합니다~

2024-08-21 11:50 UTC, realisshomyang approved these changes
고생하셨습니다!

2024-08-21 11:50 UTC, pstar987 approved these changes

2024-08-21 11:51 UTC, zestbear approved these changes
수고하셨습니 👍👍 !!

2024-08-21 11:51 UTC, merged