refactor: UserService에 DtoMapper 적용
CAUCSE/CAUSW_backend pull request #600
Opened 2024-08-28 04:15 UTC by acidify04

### 🚩 관련사항
#595 

### 📢 전달사항
UserService에서 Dto로 변환하는 경우 모두 DtoMapper를 사용하도록 변경하였습니다.
다만 UserPrivilegedDto의 경우 매핑 과정에서 계속 오류가 발생하였기 때문에 default 키워드를 사용하여 직접 구현했습니다.
이 부분은 의견 주시면 바로 적용하도록 하겠습니다.
또한 UserService의 거의 모든 메소드를 리팩토링했기 때문에 테스트는 하지 못했습니다. 테스트가 반드시 필요하다면 천천히라도 테스트 진행하도록 하겠습니다!

### 📸 스크린샷
<img width="788" alt="image" src="https://github.com/user-attachments/assets/2dcae69b-a301-44a9-b7a9-ada11f5a40ce">

### 📃 진행사항
- [ ] 필요시 테스트 진행

### ⚙️ 기타사항
기타 참고사항을 적어주세요.

개발기간:

2024-08-28 05:29 UTC, pstar987 requested changes
번거로운 작업 고생하셨습니다! 다만 테스트는 반드시 필요하기 때문에 테스트도 완료해주셔야 할 것 같습니다!

2024-08-28 05:29 UTC, pstar987 commented on src/main/java/net/causw/application/user/UserService.java
> +                        this.postRepository.countAllCommentByPost_Id(post.getId())
이부분처럼 dtomapper의 파라미터로 모든것을 넘겨주면 dtomapper와 기존 of 생성자의 차이가 없는것 같습니다. 파라미터로 post.getBoard().getId()를 하나하나 넘겨주는게 아닌 파라미터로는 post, board 등 엔티티 만을 넘겨주고 dtomapper내부에서 @Mapping으로 dto 내부 요소에 매핑 시켜주는게 좋을 것 같습니다. 수정하게 된다면 다른 메서드들도 그렇게 수정해주시면 좋을 것 같습니다. 다른분들은 어떻게 생각하시는지 의견 들어보고 싶습니다!

2024-08-28 05:29 UTC, pstar987 commented on src/main/java/net/causw/application/user/UserService.java
> +                            ownCircles.stream().map(Circle::getId).collect(Collectors.toList())))
이부분은 circleid가 위에도 있는데 혹시 잘못 수정하신거 아닌지 확인 부탁드립니다.

2024-08-28 05:36 UTC, acidify04 commented on src/main/java/net/causw/application/user/UserService.java
> +                            ownCircles.stream().map(Circle::getId).collect(Collectors.toList())))
앗 잘못 수정한 것 맞습니다 수정해서 다시 push했습니다! 감사합니다

2024-08-29 14:58 UTC, zestbear reviewed
수고하셨습니다! 세분화 너무 잘 하셨지만 다음 회의에서 커밋 단위와 커밋 룰을 통일해야할 필요성이 있을 것 같습니다.

2024-08-29 17:22 UTC, givemethatsewon commented on src/main/java/net/causw/application/user/UserService.java
> +        return DtoMapper.INSTANCE.toUserResponseDto(requestUser, getCircleIdsIfLeader(requestUser), getCircleNamesIfLeader(requestUser));
질문이 있는데 여기서 Circle 관련 정보를 받아야 하는 이유가 있을까요? 다른 부분에서 toUserReponseDto를 사용할 때는 뒤 부분을 null로 받기도 해서 여쭤봅니다.

2024-08-29 21:16 UTC, acidify04 commented
> 수고하셨습니다! 세분화 너무 잘 하셨지만 개발하시는 분들의 커밋 스타일 차이가 크다보니 다음 회의에서는 커밋 단위와 커밋 룰을 통일해야할 필요성이 있을 것 같습니다.

확인했습니다! 다음부터는 다음 회의 때 정해진 커밋 룰 따라서 커밋하도록 하겠습니다. 감사합니다!

2024-08-30 00:31 UTC, OH-GITAEK approved these changes
확인했습니다~~ 작업 하시느라 고생하셨습니다!

2024-08-30 00:32 UTC, OH-GITAEK commented on src/main/java/net/causw/application/user/UserService.java
> +                        this.postRepository.countAllCommentByPost_Id(post.getId())
저도 엔티티만 넘겨주고 dtoMapper에서 처리하는것이 더 좋아보입니다!

2024-08-30 02:16 UTC, sinseongseop commented
코드 수정 확인했습니다. 수고하셨습니다!

2024-08-30 02:16 UTC, sinseongseop approved these changes

2024-08-30 15:00 UTC, acidify04 commented on src/main/java/net/causw/application/user/UserService.java
> +                        this.postRepository.countAllCommentByPost_Id(post.getId())
그러면 그 방향으로 수정하도록 하겠습니다!

2024-09-02 06:19 UTC, win-luck approved these changes
고생하셨습니다~! 다만 앞서 언급되었다시피 커밋 메시지의 형식만 약간 개선해봐도 좋을 것 같네요.

2024-09-02 06:19 UTC, win-luck commented on src/main/java/net/causw/application/user/UserService.java
> +        return DtoMapper.INSTANCE.toUserSignOutResponseDto("로그아웃 성공");
하드코딩된 문자열만 MessageUtil로 옮겨주시면 감사하겠습니다.

2024-09-02 12:39 UTC, pstar987 approved these changes

2024-09-03 11:36 UTC, pstar987 commented on src/main/java/net/causw/application/user/UserService.java
> +        return DtoMapper.INSTANCE.toUserSignOutResponseDto("로그아웃 성공");
네 추가해주시면 될 것 같습니다

2024-09-03 12:21 UTC, merged